trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 8.1

jobs:
- job: Michael_Sutjiato
  steps:
  - script: |
      sudo update-alternatives --set php /usr/bin/php$(phpVersion)
      # ... (rest of the PHP setup)
      php -version
    displayName: 'Use PHP version $(phpVersion)'

  - script: composer install --no-interaction --prefer-dist
    displayName: 'Install Composer dependencies'

  - script: |
      # Create a dummy config file to prevent errors
      echo "<?php define('SITE_URL', 'http://localhost'); ?>" > config/config.php
      echo "<?php class Database { public function __construct() {} public function connect() { return $this; } public function beginTransaction() {} public function rollBack() {} public function fetchAll() { return []; } public function fetch() { return null; } public function query() {} public function lastInsertId() { return 1; } public function createDatabaseIfNotExists() {} } ?>" > config/database.php
    displayName: 'Create dummy config files'

  - script: ./vendor/bin/phpunit --verbose --testsuite "Michael_Sutjiato_Tests" --log-junit "junit-michael.xml"
    displayName: "Run Michael Sutjiato's Tests"
    # We add continueOnError so the next step runs even if tests fail
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit-michael.xml'
      testRunTitle: "Michael Sutjiato's Test Results"
    condition: succeededOrFailed()